name: Laravel Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      APP_URL: "http://127.0.0.1:8080"
      APP_ENV: "testing"
      DB_DATABASE: db_testing
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, sqlite, pdo_sqlite
          coverage: none
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE \`db_testing\` character set UTF8mb4 collate utf8mb4_bin;"

      - name: Run Migration
        run: php artisan migrate

      - name: Run Seeder
        run: php artisan db:seed

      - name: Run Development Seeder
        run: php artisan db:seed DevelopmentSeeder

      - name: Clear config, route, and view cache
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan cache:clear

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit
